### ISSUE TITLE
Import Bootstrap

### ISSUE THREAD

**Issue by Bosterm** [alexdryden/default#10]
Need to import bootstrap or another CSS framework for responsive columns and grid layout.

**Comment by alexdryden** [comment]
@Bosterm one thing that I noticed today is that you can't use the the bootstrap classes in the SCSS pages because we are getting those stylesheets from the content delivery network as a head link. Do you think it is worth it to instead include the bootstrap files in the assets so that we can reference them directly in the SCSS?

The example where I was running into it was wanting to add the `shadow-lg` class to the `nav-card` class on hover.

**Comment by Bosterm** [comment]
Yes when I use bootstrap I just get the files themselves and not the CDN so that I have a bit more control over what bootstrap does. It would probably be a good idea for us to do that.

**Comment by alexdryden** [comment]
Okay, that makes sense. I'm going to go ahead and open this back up then. Omeka is generally using composer for external libraries, so I think I can just go that route.
